# Generated by Django 5.2.4 on 2025-08-04 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ClientSendBookingNotigicationToAdmin', 'Уведомление о бронировании от клиента к админу'), ('BookingConfirmed', 'Бронирование подтверждено'), ('BookingCancelled', 'Бронирование отменено'), ('PaymentReceived', 'Платеж получен'), ('PaymentFailed', 'Ошибка платежа'), ('ServiceUpdated', 'Услуга обновлена'), ('NewMessage', 'Новое сообщение'), ('SystemAlert', 'Системное уведомление')], max_length=100)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Дополнительные данные уведомления')),
                ('status', models.CharField(choices=[('unread', 'Не прочитано'), ('read', 'Прочитано'), ('deleted', 'Удалено')], default='unread', max_length=20)),
                ('fcm_token', models.CharField(blank=True, help_text='Firebase FCM токен устройства', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_7088ed_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
