# Generated by Django 4.2.7 on 2025-08-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['provider', 'day_of_week'], name='services_sc_provide_dd693a_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['service', 'day_of_week'], name='services_sc_service_8deef5_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['is_available'], name='services_sc_is_avai_da5101_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['created_at'], name='services_sc_created_322274_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['provider', 'created_at'], name='services_se_provide_322654_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['price'], name='services_se_price_4a7bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['created_at'], name='services_se_created_ebde2c_idx'),
        ),
    ]
