# Generated by Django 5.2.4 on 2025-08-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminIssue',
        ),
    ]
