# Generated by Django 5.2.4 on 2025-07-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='requested_at',
            new_name='created_at',
        ),
    ]
