# Generated by Django 5.2.4 on 2025-08-03 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_passwordresetcode_delete_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider'), ('management', 'Management'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('accountant', 'Accountant')], default='customer', max_length=25),
        ),
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('user_management', 'User Management'), ('service_management', 'Service Management'), ('booking_management', 'Booking Management'), ('payment_management', 'Payment Management'), ('withdrawal_management', 'Withdrawal Management'), ('document_management', 'Document Management'), ('financial_reports', 'Financial Reports'), ('system_settings', 'System Settings'), ('admin_management', 'Admin Management')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Permission',
                'verbose_name_plural': 'Admin Permissions',
                'unique_together': {('admin_user', 'permission')},
            },
        ),
    ]
