# Generated by Django 5.2.4 on 2025-08-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_user_role_adminpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider'), ('management', 'Support Manager'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('accountant', 'Accountant')], default='customer', max_length=25),
        ),
    ]
