# Generated by Django 4.2.7 on 2025-08-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='currency',
            field=models.CharField(default='usd', max_length=10),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
