# Generated by Django 5.2.4 on 2025-07-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_provider_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
