# Generated by Django 5.2.4 on 2025-08-04 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('bookings_export', 'Экспорт бронирований'), ('payments_export', 'Экспорт платежей'), ('users_export', 'Экспорт пользователей'), ('services_export', 'Экспорт услуг'), ('data_cleanup', 'Очистка данных'), ('data_analysis', 'Анализ данных'), ('report_generation', 'Генерация отчетов')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('batch_size', models.IntegerField(default=100, help_text='Размер пакета для обработки')),
                ('total_records', models.IntegerField(default=0, help_text='Общее количество записей')),
                ('processed_records', models.IntegerField(default=0, help_text='Обработанных записей')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Фильтры для данных')),
                ('date_from', models.DateTimeField(blank=True, help_text='Дата начала периода', null=True)),
                ('date_to', models.DateTimeField(blank=True, help_text='Дата окончания периода', null=True)),
                ('result_file', models.CharField(blank=True, help_text='Путь к файлу результата', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Сообщение об ошибке', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача обработки данных',
                'verbose_name_plural': 'Задачи обработки данных',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField(help_text='Номер пакета')),
                ('start_record', models.IntegerField(help_text='Начальная запись')),
                ('end_record', models.IntegerField(help_text='Конечная запись')),
                ('records_processed', models.IntegerField(default=0, help_text='Обработанных записей в пакете')),
                ('is_completed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='workers.dataprocessingtask')),
            ],
            options={
                'ordering': ['batch_number'],
                'unique_together': {('task', 'batch_number')},
            },
        ),
    ]
