# Generated by Django 4.2.7 on 2025-08-18 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, help_text='Service location/address', max_length=255, null=True)),
                ('preferred_date', models.DateField(blank=True, help_text='Preferred service date', null=True)),
                ('preferred_time', models.TimeField(blank=True, help_text='Preferred service time', null=True)),
                ('frequency', models.CharField(choices=[('one_time', 'One Time'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='one_time', help_text='Service frequency', max_length=20)),
                ('scheduled_datetime', models.DateTimeField(blank=True, help_text='Actual scheduled date and time', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from customer', null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('google_calendar_event_id', models.CharField(blank=True, help_text='Google Calendar event ID', max_length=255, null=True)),
                ('calendar_invitations_sent', models.BooleanField(default=False, help_text='Whether calendar invitations were sent')),
                ('calendar_sent_at', models.DateTimeField(blank=True, help_text='When calendar invitations were sent', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
