# Generated by Django 5.2.4 on 2025-08-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.AddField(
            model_name='booking',
            name='frequency',
            field=models.CharField(choices=[('one_time', 'One Time'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='one_time', help_text='Service frequency', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, help_text='Service location/address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes from customer', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_date',
            field=models.DateField(blank=True, help_text='Preferred service date', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_time',
            field=models.TimeField(blank=True, help_text='Preferred service time', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, help_text='Actual scheduled date and time', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
