# Generated by Django 4.2.7 on 2025-08-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status'], name='bookings_bo_custome_0cbf77_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['provider', 'status'], name='bookings_bo_provide_c56754_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service', 'status'], name='bookings_bo_service_b2b755_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['scheduled_datetime'], name='bookings_bo_schedul_8a0f72_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_bo_created_1720a2_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['customer', 'status'], name='bookings_in_custome_970770_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['provider', 'status'], name='bookings_in_provide_472588_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['service', 'status'], name='bookings_in_service_c28420_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['scheduled_datetime'], name='bookings_in_schedul_d77b86_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['created_at'], name='bookings_in_created_c62e48_idx'),
        ),
    ]
