# Generated by Django 4.2.7 on 2025-08-20 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_interviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
