# Generated by Django 5.2.4 on 2025-08-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_remove_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='calendar_invitations_sent',
            field=models.BooleanField(default=False, help_text='Whether calendar invitations were sent'),
        ),
        migrations.AddField(
            model_name='booking',
            name='calendar_sent_at',
            field=models.DateTimeField(blank=True, help_text='When calendar invitations were sent', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID', max_length=255, null=True),
        ),
    ]
