# Generated by Django 4.2.7 on 2025-08-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_email_verification_code_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpermission',
            options={'ordering': ['permission_name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('hr', 'HR'), ('supervisor', 'Supervisor'), ('customer', 'Customer'), ('service_provider', 'Service Provider')], default='customer', max_length=20),
        ),
    ]
